/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.21.12
// source: accounts.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as accounts_pb from './accounts_pb'; // proto import: "accounts.proto"


export class AccountServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCreateAccount = new grpcWeb.MethodDescriptor(
    '/AccountService/CreateAccount',
    grpcWeb.MethodType.UNARY,
    accounts_pb.AccountRequest,
    accounts_pb.AccountResponse,
    (request: accounts_pb.AccountRequest) => {
      return request.serializeBinary();
    },
    accounts_pb.AccountResponse.deserializeBinary
  );

  createAccount(
    request: accounts_pb.AccountRequest,
    metadata?: grpcWeb.Metadata | null): Promise<accounts_pb.AccountResponse>;

  createAccount(
    request: accounts_pb.AccountRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: accounts_pb.AccountResponse) => void): grpcWeb.ClientReadableStream<accounts_pb.AccountResponse>;

  createAccount(
    request: accounts_pb.AccountRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: accounts_pb.AccountResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/AccountService/CreateAccount',
        request,
        metadata || {},
        this.methodDescriptorCreateAccount,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/AccountService/CreateAccount',
    request,
    metadata || {},
    this.methodDescriptorCreateAccount);
  }

  methodDescriptorLogin = new grpcWeb.MethodDescriptor(
    '/AccountService/Login',
    grpcWeb.MethodType.UNARY,
    accounts_pb.LoginRequest,
    accounts_pb.LoginResponse,
    (request: accounts_pb.LoginRequest) => {
      return request.serializeBinary();
    },
    accounts_pb.LoginResponse.deserializeBinary
  );

  login(
    request: accounts_pb.LoginRequest,
    metadata?: grpcWeb.Metadata | null): Promise<accounts_pb.LoginResponse>;

  login(
    request: accounts_pb.LoginRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: accounts_pb.LoginResponse) => void): grpcWeb.ClientReadableStream<accounts_pb.LoginResponse>;

  login(
    request: accounts_pb.LoginRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: accounts_pb.LoginResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/AccountService/Login',
        request,
        metadata || {},
        this.methodDescriptorLogin,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/AccountService/Login',
    request,
    metadata || {},
    this.methodDescriptorLogin);
  }

  methodDescriptorGetProfile = new grpcWeb.MethodDescriptor(
    '/AccountService/GetProfile',
    grpcWeb.MethodType.UNARY,
    accounts_pb.ProfileRequest,
    accounts_pb.ProfileResponse,
    (request: accounts_pb.ProfileRequest) => {
      return request.serializeBinary();
    },
    accounts_pb.ProfileResponse.deserializeBinary
  );

  getProfile(
    request: accounts_pb.ProfileRequest,
    metadata?: grpcWeb.Metadata | null): Promise<accounts_pb.ProfileResponse>;

  getProfile(
    request: accounts_pb.ProfileRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: accounts_pb.ProfileResponse) => void): grpcWeb.ClientReadableStream<accounts_pb.ProfileResponse>;

  getProfile(
    request: accounts_pb.ProfileRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: accounts_pb.ProfileResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/AccountService/GetProfile',
        request,
        metadata || {},
        this.methodDescriptorGetProfile,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/AccountService/GetProfile',
    request,
    metadata || {},
    this.methodDescriptorGetProfile);
  }

}

