# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: jogo.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'jogo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\njogo.proto\x12\rturnbasedgame\"$\n\x0fJoinGameRequest\x12\x11\n\tplayer_id\x18\x01 \x01(\t\"3\n\x10JoinGameResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"q\n\x0bTurnRequest\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x14\n\x0c\x61ttack_power\x18\x03 \x01(\x05\x12\x15\n\rdefense_power\x18\x04 \x01(\x05\x12\x12\n\nheal_power\x18\x05 \x01(\x05\"\\\n\x0cTurnResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\rplayer_health\x18\x03 \x01(\x05\x12\x14\n\x0c\x65nemy_health\x18\x04 \x01(\x05\"#\n\x10GameStateRequest\x12\x0f\n\x07game_id\x18\x01 \x01(\t\"\xb1\x01\n\x11GameStateResponse\x12\x0f\n\x07player1\x18\x01 \x01(\t\x12\x0f\n\x07player2\x18\x02 \x01(\t\x12\x31\n\rplayer1_state\x18\x03 \x01(\x0b\x32\x1a.turnbasedgame.PlayerState\x12\x31\n\rplayer2_state\x18\x04 \x01(\x0b\x32\x1a.turnbasedgame.PlayerState\x12\x14\n\x0c\x63urrent_turn\x18\x05 \x01(\t\",\n\x0bPlayerState\x12\n\n\x02hp\x18\x01 \x01(\x05\x12\x11\n\tdefending\x18\x02 \x01(\x08\x32\xf4\x01\n\rTurnBasedGame\x12K\n\x08JoinGame\x12\x1e.turnbasedgame.JoinGameRequest\x1a\x1f.turnbasedgame.JoinGameResponse\x12\x43\n\x08TakeTurn\x12\x1a.turnbasedgame.TurnRequest\x1a\x1b.turnbasedgame.TurnResponse\x12Q\n\x0cGetGameState\x12\x1f.turnbasedgame.GameStateRequest\x1a .turnbasedgame.GameStateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jogo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JOINGAMEREQUEST']._serialized_start=29
  _globals['_JOINGAMEREQUEST']._serialized_end=65
  _globals['_JOINGAMERESPONSE']._serialized_start=67
  _globals['_JOINGAMERESPONSE']._serialized_end=118
  _globals['_TURNREQUEST']._serialized_start=120
  _globals['_TURNREQUEST']._serialized_end=233
  _globals['_TURNRESPONSE']._serialized_start=235
  _globals['_TURNRESPONSE']._serialized_end=327
  _globals['_GAMESTATEREQUEST']._serialized_start=329
  _globals['_GAMESTATEREQUEST']._serialized_end=364
  _globals['_GAMESTATERESPONSE']._serialized_start=367
  _globals['_GAMESTATERESPONSE']._serialized_end=544
  _globals['_PLAYERSTATE']._serialized_start=546
  _globals['_PLAYERSTATE']._serialized_end=590
  _globals['_TURNBASEDGAME']._serialized_start=593
  _globals['_TURNBASEDGAME']._serialized_end=837
# @@protoc_insertion_point(module_scope)
