# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import jogo_pb2 as jogo__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in jogo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TurnBasedGameStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.JoinGame = channel.unary_unary(
                '/turnbasedgame.TurnBasedGame/JoinGame',
                request_serializer=jogo__pb2.JoinGameRequest.SerializeToString,
                response_deserializer=jogo__pb2.JoinGameResponse.FromString,
                _registered_method=True)
        self.TakeTurn = channel.unary_unary(
                '/turnbasedgame.TurnBasedGame/TakeTurn',
                request_serializer=jogo__pb2.TurnRequest.SerializeToString,
                response_deserializer=jogo__pb2.TurnResponse.FromString,
                _registered_method=True)
        self.GetGameState = channel.unary_unary(
                '/turnbasedgame.TurnBasedGame/GetGameState',
                request_serializer=jogo__pb2.GameStateRequest.SerializeToString,
                response_deserializer=jogo__pb2.GameStateResponse.FromString,
                _registered_method=True)


class TurnBasedGameServicer(object):
    """Missing associated documentation comment in .proto file."""

    def JoinGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TakeTurn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGameState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TurnBasedGameServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'JoinGame': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinGame,
                    request_deserializer=jogo__pb2.JoinGameRequest.FromString,
                    response_serializer=jogo__pb2.JoinGameResponse.SerializeToString,
            ),
            'TakeTurn': grpc.unary_unary_rpc_method_handler(
                    servicer.TakeTurn,
                    request_deserializer=jogo__pb2.TurnRequest.FromString,
                    response_serializer=jogo__pb2.TurnResponse.SerializeToString,
            ),
            'GetGameState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGameState,
                    request_deserializer=jogo__pb2.GameStateRequest.FromString,
                    response_serializer=jogo__pb2.GameStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'turnbasedgame.TurnBasedGame', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('turnbasedgame.TurnBasedGame', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TurnBasedGame(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def JoinGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/turnbasedgame.TurnBasedGame/JoinGame',
            jogo__pb2.JoinGameRequest.SerializeToString,
            jogo__pb2.JoinGameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TakeTurn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/turnbasedgame.TurnBasedGame/TakeTurn',
            jogo__pb2.TurnRequest.SerializeToString,
            jogo__pb2.TurnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGameState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/turnbasedgame.TurnBasedGame/GetGameState',
            jogo__pb2.GameStateRequest.SerializeToString,
            jogo__pb2.GameStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
