# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: accounts.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'accounts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61\x63\x63ounts.proto\"C\n\x0e\x41\x63\x63ountRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"2\n\x0f\x41\x63\x63ountResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\".\n\rLoginResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\"\x1f\n\x0eProfileRequest\x12\r\n\x05token\x18\x01 \x01(\t\"B\n\x0fProfileResponse\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t2\x9d\x01\n\x0e\x41\x63\x63ountService\x12\x32\n\rCreateAccount\x12\x0f.AccountRequest\x1a\x10.AccountResponse\x12&\n\x05Login\x12\r.LoginRequest\x1a\x0e.LoginResponse\x12/\n\nGetProfile\x12\x0f.ProfileRequest\x1a\x10.ProfileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'accounts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACCOUNTREQUEST']._serialized_start=18
  _globals['_ACCOUNTREQUEST']._serialized_end=85
  _globals['_ACCOUNTRESPONSE']._serialized_start=87
  _globals['_ACCOUNTRESPONSE']._serialized_end=137
  _globals['_LOGINREQUEST']._serialized_start=139
  _globals['_LOGINREQUEST']._serialized_end=186
  _globals['_LOGINRESPONSE']._serialized_start=188
  _globals['_LOGINRESPONSE']._serialized_end=234
  _globals['_PROFILEREQUEST']._serialized_start=236
  _globals['_PROFILEREQUEST']._serialized_end=267
  _globals['_PROFILERESPONSE']._serialized_start=269
  _globals['_PROFILERESPONSE']._serialized_end=335
  _globals['_ACCOUNTSERVICE']._serialized_start=338
  _globals['_ACCOUNTSERVICE']._serialized_end=495
# @@protoc_insertion_point(module_scope)
